INSERT INTO ROOM (NAME, CAPACITY, CREATED_ON, MODIFIED_ON) VALUES ('AMAZE', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ROOM (NAME, CAPACITY, CREATED_ON, MODIFIED_ON) VALUES ('STRIVE', 21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ROOM (NAME, CAPACITY, CREATED_ON, MODIFIED_ON) VALUES ('BEAUTY', 7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ROOM (NAME, CAPACITY, CREATED_ON, MODIFIED_ON) VALUES ('INSPIRE', 12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());